name: Stage the app

on: 
  pull_request:
    types: [labeled]
env:
  DOCKER_IMAGE_NAME: yusufraji-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: yusufraji-ttt-app
  #################################################

jobs:
  build:
    runs_on: ubuntu-latest

  if: contains(github.event.pull_request.labels.*.name, 'stage')
